workflows:
  ios-release-workflow: # Or whatever you named your workflow
    # ... other settings
    scripts:
      - name: Activate FlutterFire CLI
        script: | 
          dart pub global activate flutterfire_cli
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Build iOS app
        script: | 
          flutter build ipa --release 
    # ... artifacts, publishing, etc.